name: Lint Check

on: 
  push: 
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check Lint
        run: deno fmt --check
